#!/bin/bash
# ============================================================================
# CHAT-BOT: QUICK START GUIDE
# ============================================================================
# This guide shows you how to run and test the chat-bot application

echo "🚀 CHAT-BOT APPLICATION STRUCTURE"
echo "=========================================="
echo ""
echo "📦 Services (Running on these ports):"
echo "  • Web Frontend      → http://localhost:3000 (Next.js)"
echo "  • API Server        → http://localhost:4000 (Express)"
echo "  • AI Service        → http://localhost:8001 (FastAPI/Python)"
echo "  • PostgreSQL        → localhost:5432"
echo "  • Redis Cache       → localhost:6379"
echo ""

echo "📋 OPTION 1: RUN EVERYTHING WITH DOCKER (Recommended)"
echo "=========================================="
echo ""
echo "# Start all services"
echo "  docker-compose up -d"
echo ""
echo "# Or with build (if you made code changes)"
echo "  docker-compose up -d --build"
echo ""
echo "# View logs"
echo "  docker-compose logs -f"
echo "  docker-compose logs -f ai-service"
echo ""
echo "# Stop everything"
echo "  docker-compose down"
echo ""

echo "📋 OPTION 2: RUN LOCALLY (Development)"
echo "=========================================="
echo ""
echo "# 1. Start Docker infrastructure only (DB, Redis, AI-service)"
echo "  make db-up"
echo ""
echo "# 2. Install dependencies"
echo "  pnpm install"
echo ""
echo "# 3. In separate terminals, start the dev servers:"
echo ""
echo "  # Terminal 1: Web Frontend"
echo "    cd apps/web"
echo "    pnpm dev"
echo ""
echo "  # Terminal 2: API Server"
echo "    cd apps/api"
echo "    pnpm dev"
echo ""
echo "  # Terminal 3: AI Service (Python)"
echo "    make dev-ai"
echo "    # OR"
echo "    cd apps/ai-service && python -m uvicorn main:app --reload --port 8001"
echo ""
echo "# Or run all at once with turbo:"
echo "  pnpm dev"
echo ""

echo "📋 OPTION 3: QUICK START (Easiest)"
echo "=========================================="
echo ""
echo "# One-liner to start everything"
echo "  pnpm start"
echo ""

echo "🧪 TESTING THE APPLICATION"
echo "=========================================="
echo ""

echo "1️⃣  Test Health Endpoints:"
echo ""
echo "   # AI Service health"
echo "     curl http://localhost:8001/health"
echo ""
echo "   # API Server health (if running)"
echo "     curl http://localhost:4000/health"
echo ""

echo "2️⃣  Test Chat Endpoint:"
echo ""
echo "   # Send a simple message"
echo "     curl -X POST http://localhost:8001/api/chat/ \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"message\":\"hello\",\"conversation_history\":[]}'"
echo ""
echo "   # Example: Ask about headphones"
echo "     curl -X POST http://localhost:8001/api/chat/ \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"message\":\"i want to buy headphones under 100 euros\",\"conversation_history\":[]}'"
echo ""

echo "3️⃣  Test Streaming Chat:"
echo ""
echo "   curl -N -X POST http://localhost:8001/api/chat/stream \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"message\":\"test\",\"conversation_history\":[]}'"
echo ""

echo "4️⃣  Test Chat Routes:"
echo ""
echo "   # Check if chat service is responding"
echo "     curl http://localhost:8001/api/chat/test"
echo ""

echo "5️⃣  Access Web Interface:"
echo ""
echo "   # Open in browser"
echo "   http://localhost:3000"
echo ""

echo "📊 USEFUL DOCKER COMMANDS"
echo "=========================================="
echo ""
echo "  # View container logs"
echo "    docker-compose logs ai-service -f"
echo "    docker-compose logs db -f"
echo ""
echo "  # Execute command in container"
echo "    docker-compose exec ai-service python -m pip list"
echo "    docker-compose exec db psql -U postgres -d chatbot_dev -c 'SELECT * FROM products LIMIT 5;'"
echo ""
echo "  # Rebuild specific service"
echo "    docker-compose up -d --build ai-service"
echo ""
echo "  # Clean everything and start fresh"
echo "    docker-compose down -v"
echo "    docker-compose up -d --build"
echo ""

echo "⚙️  MAKEFILE COMMANDS"
echo "=========================================="
echo ""
echo "  # Development with hot reload"
echo "    make dev"
echo ""
echo "  # Development AI service only"
echo "    make dev-ai"
echo ""
echo "  # Start database and redis"
echo "    make db-up"
echo ""
echo "  # Test scraper"
echo "    make scrape-test"
echo ""
echo "  # Clean up everything"
echo "    make clean"
echo ""

echo "🔍 TESTING WORKFLOW"
echo "=========================================="
echo ""
echo "Step 1: Check if services are running"
echo "  docker-compose ps"
echo ""
echo "Step 2: Verify AI service is responding"
echo "  curl http://localhost:8001/health | jq ."
echo ""
echo "Step 3: Test simple chat"
echo "  curl -X POST http://localhost:8001/api/chat/ \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"message\":\"hello\",\"conversation_history\":[]}' | jq ."
echo ""
echo "Step 4: Check web interface"
echo "  open http://localhost:3000"
echo "   (or navigate to it in your browser)"
echo ""
echo "Step 5: Try chatting in the UI"
echo "  Click on the chat and send a message"
echo ""

echo "❌ TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "Issue: Port already in use"
echo "  Solution: Kill the process or change the port"
echo "    lsof -i :8001  # Find what's using port 8001"
echo "    kill -9 <PID>"
echo ""
echo "Issue: Services not connecting"
echo "  Solution: Check if Docker containers are running"
echo "    docker-compose ps"
echo "    docker-compose logs"
echo ""
echo "Issue: Chat returns 'error'"
echo "  Solution: Check AI service logs"
echo "    docker-compose logs ai-service -f"
echo ""
echo "Issue: pnpm dependencies issue"
echo "  Solution: Clean install"
echo "    rm -rf node_modules"
echo "    pnpm install"
echo ""

echo "✅ ALL SET! You're ready to go!"
echo "=========================================="
